import { gabarito } from "./fonts";
import "./globals.css";
import Header from "@/components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${gabarito.className} antialiased w-screen h-screen flex items-center justify-center`}>
        <main className="border border-white rounded-4xl w-[94%] h-[88%] p-10 m-10">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
